<?php

return [
    'pages' => [
        'sakums' => [
            'title' => 'Sākums',
            'path' => '/',
            'fields' => [
                ['key' => 'hero_title', 'label' => 'hero_title', 'type' => 'textarea'],
                ['key' => 'hero_text', 'label' => 'hero_text', 'type' => 'textarea'],
                ['key' => 'hero_image', 'label' => 'hero_image', 'type' => 'image'],
                ['key' => 'primary_button_text', 'label' => 'primary_button_text', 'type' => 'text'],
                ['key' => 'secondary_button_text', 'label' => 'secondary_button_text', 'type' => 'text'],
                ['key' => 'about_title', 'label' => 'about_title', 'type' => 'text'],
                ['key' => 'about_text', 'label' => 'about_text', 'type' => 'textarea'],
                ['key' => 'about_image', 'label' => 'about_image', 'type' => 'image'],
                ['key' => 'services_title', 'label' => 'services_title', 'type' => 'text'],
                ['key' => 'services_text', 'label' => 'services_text', 'type' => 'textarea'],
            ],
            'defaults' => [
                'hero_title' => 'Uzticams partneris būvniecībā, renovācijā un īpašumu uzturēšanā',
                'hero_text' => 'SIA Top Care Group ir Latvijas uzņēmums, kas nodrošina plašu būvniecības, renovācijas un apsaimniekošanas pakalpojumu klāstu privātpersonām, uzņēmumiem un namu apsaimniekotājiem.',
                'hero_image' => '/images/profesionala-koka-logu-restauracija-jurmala.jpeg',
                'primary_button_text' => 'Saņemt cenu',
                'secondary_button_text' => 'Sazināties WhatsApp',
                'about_title' => 'Kvalitatīvs darbs, atbildība un godīga attieksme',
                'about_text' => "Mūsu komandu veido pieredzējuši speciālisti, kuri ikdienā strādā pie dažāda mēroga projektiem visā Latvijā.\n\nMēs ticam, ka kvalitatīvs darbs, atbildība un godīga attieksme ir pamats ilgtermiņa sadarbībai ar klientiem.",
                'about_image' => '/images/privatmajas-renovacija-latvija.jpeg',
                'services_title' => 'Būtiskākie Top Care Group virzieni',
                'services_text' => 'Pārskatāms pakalpojumu klāsts privātmājām, komerciāliem objektiem un apsaimniekošanas vajadzībām visā Latvijā.',
            ],
        ],
        'pakalpojumi' => [
            'title' => 'Pakalpojumi',
            'path' => '/pakalpojumi',
            'fields' => [
                ['key' => 'page_title', 'label' => 'page_title', 'type' => 'text'],
                ['key' => 'page_text', 'label' => 'page_text', 'type' => 'textarea'],
            ],
            'defaults' => [
                'page_title' => 'Pakalpojumi dažāda mēroga objektiem',
                'page_text' => 'No nelieliem remonta darbiem līdz pilna cikla būvniecības un renovācijas projektiem. Katra pakalpojumu grupa ir veidota kā atsevišķa karte ar konkrētu darbu piemēriem.',
            ],
        ],
        'galerija' => [
            'title' => 'Galerija',
            'path' => '/galerija',
            'fields' => [
                ['key' => 'page_title', 'label' => 'page_title', 'type' => 'text'],
                ['key' => 'page_text', 'label' => 'page_text', 'type' => 'textarea'],
            ],
            'defaults' => [
                'page_title' => 'Darbi un ikdienas process',
                'page_text' => 'Apskatiet Top Care Group paveiktos darbus, darba procesu un ikdienas objektos visā Latvijā.',
            ],
        ],
        'par-mums' => [
            'title' => 'Par mums',
            'path' => '/par-mums',
            'fields' => [
                ['key' => 'page_title', 'label' => 'page_title', 'type' => 'text'],
                ['key' => 'page_text', 'label' => 'page_text', 'type' => 'textarea'],
                ['key' => 'main_image', 'label' => 'main_image', 'type' => 'image'],
                ['key' => 'values_title', 'label' => 'values_title', 'type' => 'text'],
                ['key' => 'value_1_title', 'label' => 'value_1_title', 'type' => 'text'],
                ['key' => 'value_1_text', 'label' => 'value_1_text', 'type' => 'textarea'],
                ['key' => 'value_2_title', 'label' => 'value_2_title', 'type' => 'text'],
                ['key' => 'value_2_text', 'label' => 'value_2_text', 'type' => 'textarea'],
                ['key' => 'value_3_title', 'label' => 'value_3_title', 'type' => 'text'],
                ['key' => 'value_3_text', 'label' => 'value_3_text', 'type' => 'textarea'],
                ['key' => 'process_title', 'label' => 'process_title', 'type' => 'text'],
                ['key' => 'process_1_title', 'label' => 'process_1_title', 'type' => 'text'],
                ['key' => 'process_2_title', 'label' => 'process_2_title', 'type' => 'text'],
                ['key' => 'process_3_title', 'label' => 'process_3_title', 'type' => 'text'],
                ['key' => 'process_4_title', 'label' => 'process_4_title', 'type' => 'text'],
            ],
            'defaults' => [
                'page_title' => 'Top Care Group',
                'page_text' => "SIA Top Care Group nodrošina būvniecības, renovācijas un īpašumu uzturēšanas pakalpojumus privātpersonām, uzņēmumiem un namu apsaimniekotājiem visā Latvijā.\n\nMūsu komandu veido pieredzējuši speciālisti, kuri strādā ar precizitāti, atbildību un skaidru izpratni par kvalitāti katrā projekta posmā.\n\nMēs veidojam ilgtermiņā uzticamus risinājumus un pieeju, kas pielāgota klienta objektam, termiņiem un darba apjomam.",
                'main_image' => '/images/topcare-komanda.png',
                'values_title' => 'Principi, uz kuriem balstām katru projektu',
                'value_1_title' => 'Kvalitāte',
                'value_1_text' => 'Strādājam rūpīgi un koncentrējamies uz ilgtermiņa rezultātu.',
                'value_2_title' => 'Atbildība',
                'value_2_text' => 'Ievērojam termiņus un uzņemamies atbildību par paveikto darbu.',
                'value_3_title' => 'Uzticēšanās',
                'value_3_text' => 'Veidojam ilgtermiņa sadarbību ar klientiem visā Latvijā.',
                'process_title' => 'Skaidrs process no pirmās sarunas līdz rezultāta nodošanai',
                'process_1_title' => 'Objekta novērtēšana',
                'process_2_title' => 'Piedāvājuma sagatavošana',
                'process_3_title' => 'Darbu izpilde',
                'process_4_title' => 'Rezultāta nodošana klientam',
            ],
        ],
        'pirms-pec' => [
            'title' => 'Pirms / Pēc',
            'path' => '/pirms-pec',
            'fields' => [
                ['key' => 'page_title', 'label' => 'page_title', 'type' => 'text'],
                ['key' => 'page_text', 'label' => 'page_text', 'type' => 'textarea'],
                ['key' => 'hero_image', 'label' => 'hero_image', 'type' => 'image'],
            ],
            'defaults' => [
                'page_title' => "Redzami rezultāti\nreālos objektos",
                'page_text' => 'Salīdziniet mūsu paveikto darbu rezultātus fasāžu, jumtu un teritoriju tīrīšanā visā Latvijā.',
                'hero_image' => '/images/fasades-mazgasana-privatmaja-jurmala.jpeg',
            ],
        ],
        'kontakti' => [
            'title' => 'Kontakti',
            'path' => '/kontakti',
            'fields' => [
                ['key' => 'page_title', 'label' => 'page_title', 'type' => 'text'],
                ['key' => 'page_text', 'label' => 'page_text', 'type' => 'textarea'],
                ['key' => 'form_button_text', 'label' => 'form_button_text', 'type' => 'text'],
            ],
            'defaults' => [
                'page_title' => 'Top Care Group',
                'page_text' => 'Ja jums nepieciešami renovācijas, apdares, fasāžu, jumtu, bruģēšanas vai īpašumu uzturēšanas darbi, sazinieties ar mums un mēs sagatavosim piemērotu risinājumu.',
                'form_button_text' => 'Nosūtīt pieteikumu',
            ],
        ],
        'privatuma-politika' => [
            'title' => 'Privātuma politika',
            'path' => '/privatuma-politika',
            'fields' => [
                ['key' => 'page_title', 'label' => 'page_title', 'type' => 'text'],
                ['key' => 'page_text', 'label' => 'page_text', 'type' => 'textarea'],
                ['key' => 'last_updated', 'label' => 'last_updated', 'type' => 'date'],
                ['key' => 'policy_content', 'label' => 'policy_content', 'type' => 'textarea'],
            ],
            'defaults' => [
                'page_title' => 'Privātuma politika',
                'page_text' => 'Informācija par personas datu apstrādi un aizsardzību.',
                'last_updated' => '2026-06-12',
                'policy_content' => '',
            ],
        ],
    ],
];
